In [42]:
import pandas as pd
import numpy as np
import chardet

def find_encoding(filename):
    read_file = open(filename, 'rb').read()        # 파일 읽기모드 rb는 read + 바이너리 파일( 바이너리 파일 읽을때 사용 )
    result    = chardet.detect(read_file)
    charenc   = result['encoding']
    return charenc


file_csv = 'C:/Users/ad/Desktop/일지/개인필기/과제/202012_202012_주민등록인구및세대현황_연간.csv'
my_encoding = find_encoding(file_csv)
df_1 = pd.read_csv(file_csv, encoding = my_encoding)
#df_0 = pd.read_csv(file_csv, encoding = )
print(my_encoding)
df_1

EUC-KR

,행정구역,2020년_거주자 인구수,2020년_세대수,2020년_세대당 인구,2020년_남자 인구수,2020년_여자 인구수,2020년_남여 비율
0,서울특별시 (1100000000),"9,505,868","4,294,290",2.21,"4,623,790","4,882,078",0.95
1,서울특별시 종로구 (1111000000),"144,017","70,734",2.04,"70,140","73,877",0.95
2,서울특별시 종로구 청운효자동(1111051500),"12,057","5,098",2.37,"5,628","6,429",0.88
3,서울특별시 종로구 사직동(1111053000),"9,080","4,431",2.05,"4,085","4,995",0.82
4,서울특별시 종로구 삼청동(1111054000),"2,492","1,220",2.04,"1,211","1,281",0.95
...,...,...,...,...,...,...,...
3841,제주특별자치도 서귀포시 서홍동(5013058000),"10,572","4,321",2.45,"5,227","5,345",0.98
3842,제주특별자치도 서귀포시 대륜동(5013059000),"14,651","6,402",2.29,"7,403","7,248",1.02
3843,제주특별자치도 서귀포시 대천동(5013060000),"13,851","6,328",2.19,"7,064","6,787",1.04
3844,제주특별자치도 서귀포시 중문동(5013061000),"11,522","5,473",2.11,"5,938","5,584",1.06
3845,제주특별자치도 서귀포시 예래동(5013062000),"3,897","1,949",2.00,"2,002","1,895",1.06

In [6]:
df_1.columns= ['행정구역', '총인구수', '세대수', '세대당인구', '남자', '여자', '남녀비율']
# df_1.rename(columns={"2020년_거주자 인구수": "총인구수", "2020년_세대수":"세대수", "기존컬럼":"변경컬럼"....})
# rename은 inplace 지원
# columns는 컬럼 elements수 맞춰줘야함(기존컬럼 7개면 columns로 넣을 컬럼도 7개여야 함)

df_2 = df_1.drop("남녀비율", axis=1)
# df_1.drop("남녀비율", axis=1, inplace=True)

df_2["행정구역"] = df_2["행정구역"].str.replace(pat=r'[^\w]', repl=r'', regex=True)
# df_1["행정구역"] = df_2["행정구역"].str.split('(').str.get(0)

,행정구역,총인구수,세대수,세대당인구,남자,여자
0,서울특별시1100000000,"9,505,868","4,294,290",2.21,"4,623,790","4,882,078"
1,서울특별시종로구1111000000,"144,017","70,734",2.04,"70,140","73,877"
2,서울특별시종로구청운효자동1111051500,"12,057","5,098",2.37,"5,628","6,429"
3,서울특별시종로구사직동1111053000,"9,080","4,431",2.05,"4,085","4,995"
4,서울특별시종로구삼청동1111054000,"2,492","1,220",2.04,"1,211","1,281"
...,...,...,...,...,...,...
3841,제주특별자치도서귀포시서홍동5013058000,"10,572","4,321",2.45,"5,227","5,345"
3842,제주특별자치도서귀포시대륜동5013059000,"14,651","6,402",2.29,"7,403","7,248"
3843,제주특별자치도서귀포시대천동5013060000,"13,851","6,328",2.19,"7,064","6,787"
3844,제주특별자치도서귀포시중문동5013061000,"11,522","5,473",2.11,"5,938","5,584"
3845,제주특별자치도서귀포시예래동5013062000,"3,897","1,949",2.00,"2,002","1,895"

In [49]:
df_2['시'] = df_2['행정구역'].str.split().str.get(0)
df_2['구'] = df_2['행정구역'].str.split().str.get(1)
df_2['동'] = df_2['행정구역'].str.split().str.get(2)

In [35]:
df_2["시"] = df_2["행정구역"].str.split('시').str[0]
df_2["구"] = (df_2["행정구역"].str.split('시').str[1]).str.split('구').str[0]
df_2

,행정구역,총인구수,세대수,세대당인구,남자,여자,시,구
0,서울특별시1100000000,"9,505,868","4,294,290",2.21,"4,623,790","4,882,078",서울특별,1100000000
1,서울특별시종로구1111000000,"144,017","70,734",2.04,"70,140","73,877",서울특별,종로
2,서울특별시종로구청운효자동1111051500,"12,057","5,098",2.37,"5,628","6,429",서울특별,종로
3,서울특별시종로구사직동1111053000,"9,080","4,431",2.05,"4,085","4,995",서울특별,종로
4,서울특별시종로구삼청동1111054000,"2,492","1,220",2.04,"1,211","1,281",서울특별,종로
...,...,...,...,...,...,...,...,...
3841,제주특별자치도서귀포시서홍동5013058000,"10,572","4,321",2.45,"5,227","5,345",제주특별자치도서귀포,서홍동5013058000
3842,제주특별자치도서귀포시대륜동5013059000,"14,651","6,402",2.29,"7,403","7,248",제주특별자치도서귀포,대륜동5013059000
3843,제주특별자치도서귀포시대천동5013060000,"13,851","6,328",2.19,"7,064","6,787",제주특별자치도서귀포,대천동5013060000
3844,제주특별자치도서귀포시중문동5013061000,"11,522","5,473",2.11,"5,938","5,584",제주특별자치도서귀포,중문동5013061000
3845,제주특별자치도서귀포시예래동5013062000,"3,897","1,949",2.00,"2,002","1,895",제주특별자치도서귀포,예래동5013062000

In [ ]:
df_2 = df_2[df_2['시']=='부산광역시']

In [ ]:
df_2['시'].unique()

In [ ]:
df_2.reset_index(inplace=Ture, drop= True) # drop == 기존 인덱스 삭제

In [51]:
#5.
df_2['총인구수'] = df_2['총인구수'].str.replace(',','').astype('int')        # replace ,를  ''으로 변경
df_2['남자'] = df_2['님지'].str.replace(',','').astype('int') 
df_2['여자'] = df_2['여자'].str.replace(',','').astype('int')

In [ ]:
#6.
import matplotlib.pyplot as plt
import seaborn as sns

data_t = df_2.groupby('구')['총인구수'].sum().sort_values(ascending=False)
data_t = data_t.reset_index()

plt.figure(figsize=(10,5))
sns.barplot(data=data_t, x='구', y='총인구수', ci=None)

In [52]:
data_t = df_2.groupby('동')['총인구수'].sum().sort_values(ascending=False)
data_t = data_t.reset_index()
data_t = data_t.head(20)

data_t = df_2.groupby('구')['총인구수'].sum().sort_values(ascending=False)
data_t = data_t.reset_index()

In [57]:
import json
jsontext = open('HangJeongDong_ver20210401.geojson','r',encoding='utf-8').read()
jsondata = json.loads(jsontext)
jsondata_pick_list = []
jsondata_dong = []

for item in jsondata['features']:
    if item['properties']['sidonm'] == '제주특별자치도':
        #print(item['properties']['adm_nm'])
        item['id']=item['properties']['adm_nm'].split()[-1].strip()
        jsondata_dong.append(item['properties']['adm_nm'].split()[-1].strip())
        jsondata_pick_list.append(item)

jsondata['features'] = jsondata_pick_list
f = open('jeju_m.json','w',encoding='utf-8')
json.dump(jsondata,f)
f.close()

FileNotFoundError: [Errno 2] No such file or directory: 'HangJeongDong_ver20210401.geojson'